.\" Copyright (c) 2023 Alexander Möller <alexander.moeller@detmold.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: June 22 2023 $
.Dt TICKET 1
.Os
.Sh NAME
.Nm ticket
.Nd ticket manager for
.Xr todo 1
.Sh SYNOPSIS
.Nm
.Op options
.Op command
.Sh DESCRIPTION
.Nm
is a simple ticket manager built on
.Xr todo 1 .
.Pp
The following commands are available:
.Bl -tag -width Ds
.It Cm ld Ar keyword
Show the very next task according to
.Xr `todo 1
ld`. This can be matched with a keyword.
.Pp
.El
All other commands fall back to
.Xr todo 1 .
Therefore all options and commands available in
.Xr todo 1
are in
.Nm .
.El
.Sh SEE ALSO
.Xr todo 1
.Sh AUTHOR
.Nm
was written by
.An Alexander Möller Aq Mt alexander.moeller@detmold.com .
