#!/bin/sh

main() {
	case $1 in
		a*) add "$@" ;;
		d*) didit ;;		# provisional
		e*) edit "$@" ;;	# subfunctions not done yet
		f*) finished ;;
		ls) ls "$@" ;;
		lscon) lscon ;;		# not implemented
		lsprj) lsprj ;;		# not implemented
		p*) prio "$@" ;;
		r*) report ;;
		h*) usage ;;
		*)
	esac
}

add() {
	shift 1 && echo "(A) $(date +%F)" "$@" >> "$TODODIR/todo.txt"
}

append() {
	echo "Appending with \$@ is not yet implemented."
}

finished() {
	$PAGER "$TODODIR/done.txt"
}

didit() {
	$EDITOR "$TODODIR/todo.txt" "$TODODIR/done.txt"
}

edit() {
	case $2 in
		p*) prepend "$@" ;;	# not implemented
		a*) append "$@" ;;	# not implemented
		*) $EDITOR "$TODODIR/todo.txt"
	esac
}

ls() {
	#awk -v pat="$2" '$0 ~ pat {printf "%4s %s\n", NR, $0}' "$TODODIR/todo.txt" | sort -k2 | awk '{ce="\033[0m"}/\(A\)/{cs="\033[1;31m"}/\(B\)/{cs="\033[1;32m"}/\(C\)/{cs="\033[1;33m"}/\(D\)/{cs="\033[1;34m"}/\(E\)/{cs="\033[0m"}{print cs$0ce}'
	awk -v pat="$2" 'index($0, pat){printf "%4s %s\n", NR, $0}' "$TODODIR/todo.txt" | sort -k2 | awk '{ce="\033[0m"}/\(A\)/{cs="\033[1;31m"}/\(B\)/{cs="\033[1;33m"}/\(C\)/{cs="\033[1;32m"}/\(D\)/{cs="\033[1;34m"}/\(E\)/{cs="\033[0m"}{print cs$0ce}'
}

lscon() {
	echo "Listing contexts with \$2 is not yet implemented."
}

lsprj() {
	echo "Listing projects with \$2 is not yet implemented."
}

prepend() {
	echo "Prepending with \$@ is not yet implemented."
}

prio() {
	[ "$2" != '' ] && [ "$3" != '' ] && sed -i "$2"'s/(.)/('"$3"')/' "$TODODIR/todo.txt" && awk -v pat="$2" '{ce="\033[0m"}/\(A\)/{cs="\033[1;31m"}/\(B\)/{cs="\033[1;33m"}/\(C\)/{cs="\033[1;32m"}/\(D\)/{cs="\033[1;34m"}/\(E\)/{cs="\033[0m"}{if(NR==pat)print cs $0 ce}' "$TODODIR/todo.txt"
}

report() {
	echo "$(date +%FT%TZ) $(awk 'END{print NR}' "$TODODIR/todo.txt") $(awk 'END{print NR}' "$TODODIR/done.txt")" >> "$TODODIR/report.txt"
}

usage() { printf "todo(1) version 0.4p2 - simple todo list manager.

=> [a]dd [entry]	- Create a new entry.
=> d[one] [entry]	- Mark [entry] as done.
=> e[dit] [entry]	- Edit [entry].
=> f[inished]		- Show finished items.
=> ls			- List current todo list.
=> lscon		- List all contexts currently in use.
=> lsprj		- List all projects currently active.
=> p [entry] [priority]	- Set/Change priority of [entry] to [priority] (A-Z).
=> r[eport]		- Create a report of the day containing the number of active and finished tasks.

=> h[help]		- Show this message.
Alternatively read the manpage.

Expected environment variables:
=> EDITOR		- The editor you want to use, when opening todo.txt
=> PAGER		- The pager you want to use, when taking a look at accomplished tasks.
=> TODODIR		- The directory where associated files are stored.

todo expects your files to be in TODODIR/
	todo.txt	- Current todo list containing active items
	done.txt	- List of finished items
	report.txt	- List of reports
"
exit 0
}

[ "$1" ] || usage && main "$@"
